### ISSUE TITLE
Error creating the database.

### ISSUE THREAD

**Issue by syahmin247** [lara-zeus/zeus#12]
I get this error when trying to create database. 
![image](https://github.com/lara-zeus/zeus/assets/103813381/b4f00d4a-3e1e-44b7-a3ff-15e2cb51fec8)
.

**Comment by syahmin247** [comment]
Solved the migration issue using this method. [https://github.com/spatie/laravel-permission/discussions/2576#discussioncomment-8417545](url).

**Comment by rabol** [comment]
the link in your solution simply take me to a empty page

**Comment by atmonshi** [comment]
make sure to republish the migration for the permissions package
you can delete this file first
`database/migrations/2023_08_22_124901_add_extensions_to_forms.php`
