### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ibnudaqiqil** [lara-zeus/zeus#13]
I Found this error when install Zeus
<img width="1481" alt="image" src="https://github.com/lara-zeus/zeus/assets/38772752/55c5ea4a-326b-48cd-8687-7491f6d68734">

**Comment by atmonshi** [comment]
you need to remove the `export` package from the composer file, I haven't update it in a while, will do soon :)

**Comment by atmonshi** [comment]
fixed!
