### ISSUE TITLE
 Cannot create dashboard

### ISSUE THREAD

**Issue by janbulens** [lara-zeus/zeus#18]
When I create a new dashboard in the lara-zeus starter kit, I get the error message "The dashboard title is required" when saving. Also a I can't add a part. No idea what I'm doing wrong?

![Schermafbeelding 2024-12-01 170849](https://github.com/user-attachments/assets/9cdcad9d-9e86-4364-955b-783043e89db8)

**Comment by atmonshi** [comment]
sorry for the delay.

make sure to run composer update to get the last version and run `npm run build`
also check if there is any console errors

if the issue still persist, feel free to reopen with more details.
