### ISSUE TITLE
Error accesing layouts

### ISSUE THREAD

**Issue by albertobenavides** [lara-zeus/zeus#6]
I get this error after trying to edit or create layouts with Rain (I have the same error after and before updating Rain): 

![image](https://github.com/lara-zeus/zeus/assets/9291085/0ef02923-cc00-42d1-8d1a-80897fe307fa)

![image](https://github.com/lara-zeus/zeus/assets/9291085/139162ab-07ae-4fd4-9d77-aae6331c4d88)

**Comment by adil-abbas** [comment]
> I get this error after trying to edit or create layouts with Rain (I have the same error after and before updating Rain):
> 
> ![image](https://user-images.githubusercontent.com/9291085/254125223-0ef02923-cc00-42d1-8d1a-80897fe307fa.png)
> 
> ![image](https://user-images.githubusercontent.com/9291085/254125172-139162ab-07ae-4fd4-9d77-aae6331c4d88.png)

I'm getting this too. 
Tried with both apache and nginx server on Ubuntu 18. 04, 20.04 and 22.04.
Made sure that all the necessary libraries were installed and loaded.

**Comment by adil-abbas** [comment]
Got the solution [here](https://github.com/lara-zeus/bolt/issues/140)

**Comment by atmonshi** [comment]
IDK why I didn't get notified of this. Glad the issue was resolved.
